machine:
  features:
    kubePrism:
      enabled: true
      port: 7445
  install:
      disk: /dev/sda # The disk used for installations.
      image: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.8.3 # Allows for supplying the image used to perform the installation.
      wipe: false # Indicates if the installation disk should be wiped at installation time.
      